### ISSUE TITLE
Is there a way to connect remotely?

### ISSUE THREAD

**Issue by slerman12** [EnriqueMoran/pyBittle#1]
Hi, thank you for this library. It looks like it'll be really useful. My worry is, I may need to send commands to Bittle across long distances. Is there a way to somehow connect directly from a server?

**Comment by EnriqueMoran** [comment]
Hello, that usage is beyond the library purpose. I think you might achieve that by connecting to the same network (maybe through a VPN in case it's a private one).

**Comment by slerman12** [comment]
Thanks. Interesting, can the Bittle connect to, say, my Phone's WiFi?

Also, maybe also unrelated to the intended use of this library, but is there a way to transmit Bittle metadata from the Bittle to my computer? Kind of the opposite of what this library does.

**Comment by EnriqueMoran** [comment]
To achieve that behaviour you would need to modify your Bittle's code, making it sending the metadata you need and receive it wherever you need to use it.
