### ISSUE TITLE
Default Bluetooth name for bittle has changed to Petoi-XXX

### ISSUE THREAD

**Issue by ecolizard** [EnriqueMoran/pyBittle#3]
The default search for the device name in bluetoothManager.py has changed from BittleSPP-XXXXX to Petoi-XXX, this search name changed is needed on line 147 "Petoi" for the code to work out the box rather than passing name into the class constructor ( which isn't shown in the examples and hard for a new user to understand ).

I've tested change on windows 11 and raised a pull request.

**Comment by EnriqueMoran** [comment]
PR approved! thank you
